# Generated by Django 2.2 on 2019-04-20 06:27

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190419_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='writerprofil',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.WriterProfil'),
        ),
    ]
